### ISSUE TITLE
Crash with variadic model scope functions (Undefined offset: 0)

### ISSUE THREAD

**Issue by wi1dcard** [nunomaduro/larastan#291]
# Variadic Model Scope Issue

- Larastan Version: `v0.3.18`
- PHPStan Version: `0.11.12`
- `--level` used: 5 (default).

### Description

Short version:

Larastan crashes while analyzing invoking model's dynamic scope functions with variadic parameters. For instance:

```php
# app/User.php
class User extends Authenticatable
{
    // ...

    public function scopeOfTypes($query, ...$types)
    {
        return $query->whereIn('type', $types);
    }
}

# In controllers or console commands:
User::query()->ofTypes(0, 1, 2);
```

Output:

```
 ------ -------------------------------------------------------------- 
  Line   app/Console/Commands/QueryScopeCommand.php                    
 ------ -------------------------------------------------------------- 
         Internal error: Undefined offset: 0                           
         Run PHPStan with --debug option and post the stack trace to:  
         https://github.com/phpstan/phpstan/issues/new                 
 ------ --------------------------------------------------------------
```

### How to Reproduce the Problem

> For quickly reproducing, I create a repo [here](https://github.com/wi1dcard/larastan-variadic-model-scope) which includes minimal codes and steps. You can find what I did step by step in the commit history.

1. `git clone git@github.com:wi1dcard/larastan-variadic-model-scope.git`
2. `composer install`
3. `php artisan code:analyse --debug`

```
   ErrorException  : Undefined offset: 0

  at /Users/wi1dcard/GitHub/larastan-variadic-model-scope/vendor/phpstan/phpstan/src/Rules/FunctionCallParametersCheck.php:119
    115|                                if (!$parametersAcceptor->isVariadic() || count($parameters) === 0) {
    116|                                        break;
    117|                                }
    118| 
  > 119|                                $parameter = $parameters[count($parameters) - 1];
    120|                                $parameterType = $parameter->getType();
    121|                                if (!($parameterType instanceof ArrayType)) {
    122|                                        break;
    123|                                }
```

These outputs seem to point to a PHPStan bug. However, after working on this issue 2 days, I start to think this may cause by Larastan:

### More Information that I found so far

1. Removing [src/Methods/Pipes/ModelScopes.php#L44][larastan-src-1] could solve this issue.

2. In PHPStan v0.11.12, [src/Rules/FunctionCallParametersCheck.php#L119][phpstan-src-1] and [src/Analyser/NodeScopeResolver.php#L2083][phpstan-src-2], replace `$parameters[count($parameters) - 1];` to `array_values(array_slice($parameters, -1))[0];` (which not retrieve the last parameter by array index) also solves it.

[larastan-src-1]: https://github.com/nunomaduro/larastan/blob/b757e4b782b437657a3bbbb8a832cc362c8cd357/src/Methods/Pipes/ModelScopes.php#L44
[phpstan-src-1]: https://github.com/phpstan/phpstan/blob/56b3eb2a371b60537fd20794e24af9e7e8ed4e30/src/Rules/FunctionCallParametersCheck.php#L119
[phpstan-src-2]: https://github.com/phpstan/phpstan/blob/56b3eb2a371b60537fd20794e24af9e7e8ed4e30/src/Analyser/NodeScopeResolver.php#L2083

### My Question

1. Does removing `unset($parameters[0]);` REALLY solving the problems? Would it leave unexpected effects? Or this line of code stands because of any other reason?
2. Should I submit an issue on the PHPStan repo?

English is not my native language, but I'm trying my best. Please excuse grammar mistakes.

**Comment by ondrejmirtes** [comment]
Hi, thank you for this bug report. Posting the stack trace from the `--debug` output would help to pinpoint if this is PHPStan or Larastan issue.

**Comment by wi1dcard** [comment]
```
  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined offset: 0", "/Users/wi1dcard/GitHub/larastan-variadic-model-scope/vendor/phpstan/phpstan/src/Rules/FunctionCallParametersCheck.php")
      /Users/wi1dcard/GitHub/larastan-variadic-model-scope/vendor/phpstan/phpstan/src/Rules/FunctionCallParametersCheck.php:119

  2   PHPStan\Rules\FunctionCallParametersCheck::check(Object(Mockery_1_PHPStan_Reflection_FunctionVariantWithPhpDocs_PHPStan_Reflection_FunctionVariantWithPhpDocs), Object(NunoMaduro\Larastan\Analyser\Scope), Object(PhpParser\Node\Expr\MethodCall))
      /Users/wi1dcard/GitHub/larastan-variadic-model-scope/vendor/phpstan/phpstan/src/Rules/Methods/CallMethodsRule.php:156
```

Here [`unset($parameters[0]);`] (https://github.com/nunomaduro/larastan/blob/b757e4b782b437657a3bbbb8a832cc362c8cd357/src/Methods/Pipes/ModelScopes.php#L44) makes `$parameters`:

1. Has only 1 element;
2. Index starts 1, not 0.

So then PHPStan could not retrieve the last parameter using `$parameters[count($parameters) - 1];` above, where the exception throws.

I could not understand why Larastan unsets `$parameters[0]`. It seems the issue can be simply resolved by comment it.

**Comment by ondrejmirtes** [comment]
Could you run it without any weird Laravel error handling? For example by running PHPStan directly and just including Larastan's `extension.neon` in your `phpstan.neon`?

**Comment by wi1dcard** [comment]
*phpstan.neon*:

```neon
includes:
    - ./vendor/nunomaduro/larastan/extension.neon
parameters:
    level: 0
    paths:
        - app
```

*In Shell*:

```
➜  vendor/bin/phpstan analyse --debug
Note: Using configuration file /Users/wi1dcard/GitHub/larastan-variadic-model-scope/phpstan.neon.
/Users/wi1dcard/GitHub/larastan-variadic-model-scope/app/User.php
/Users/wi1dcard/GitHub/larastan-variadic-model-scope/app/Exceptions/Handler.php
/Users/wi1dcard/GitHub/larastan-variadic-model-scope/app/Http/Controllers/Auth/VerificationController.php
/Users/wi1dcard/GitHub/larastan-variadic-model-scope/app/Http/Controllers/Auth/LoginController.php
/Users/wi1dcard/GitHub/larastan-variadic-model-scope/app/Http/Controllers/Auth/ResetPasswordController.php
/Users/wi1dcard/GitHub/larastan-variadic-model-scope/app/Http/Controllers/Auth/RegisterController.php
/Users/wi1dcard/GitHub/larastan-variadic-model-scope/app/Http/Controllers/Auth/ForgotPasswordController.php
/Users/wi1dcard/GitHub/larastan-variadic-model-scope/app/Http/Controllers/Controller.php
/Users/wi1dcard/GitHub/larastan-variadic-model-scope/app/Http/Middleware/TrustProxies.php
/Users/wi1dcard/GitHub/larastan-variadic-model-scope/app/Http/Middleware/TrimStrings.php
/Users/wi1dcard/GitHub/larastan-variadic-model-scope/app/Http/Middleware/RedirectIfAuthenticated.php
/Users/wi1dcard/GitHub/larastan-variadic-model-scope/app/Http/Middleware/Authenticate.php
/Users/wi1dcard/GitHub/larastan-variadic-model-scope/app/Http/Middleware/CheckForMaintenanceMode.php
/Users/wi1dcard/GitHub/larastan-variadic-model-scope/app/Http/Middleware/VerifyCsrfToken.php
/Users/wi1dcard/GitHub/larastan-variadic-model-scope/app/Http/Middleware/EncryptCookies.php
/Users/wi1dcard/GitHub/larastan-variadic-model-scope/app/Http/Kernel.php
/Users/wi1dcard/GitHub/larastan-variadic-model-scope/app/Providers/AppServiceProvider.php
/Users/wi1dcard/GitHub/larastan-variadic-model-scope/app/Providers/EventServiceProvider.php
/Users/wi1dcard/GitHub/larastan-variadic-model-scope/app/Providers/BroadcastServiceProvider.php
/Users/wi1dcard/GitHub/larastan-variadic-model-scope/app/Providers/AuthServiceProvider.php
/Users/wi1dcard/GitHub/larastan-variadic-model-scope/app/Providers/RouteServiceProvider.php
/Users/wi1dcard/GitHub/larastan-variadic-model-scope/app/Console/Commands/QueryScopeCommand.php

   ErrorException  : Undefined offset: 0

  at /Users/wi1dcard/GitHub/larastan-variadic-model-scope/vendor/phpstan/phpstan/src/Analyser/NodeScopeResolver.php:2083
    2079|                               if (isset($parameters[$i])) {
    2080|                                       $assignByReference = $parameters[$i]->passedByReference()->createsNewVariable();
    2081|                                       $parameterType = $parameters[$i]->getType();
    2082|                               } elseif (count($parameters) > 0 && $parametersAcceptor->isVariadic()) {
  > 2083|                                       $lastParameter = $parameters[count($parameters) - 1];
    2084|                                       $assignByReference = $lastParameter->passedByReference()->createsNewVariable();
    2085|                                       $parameterType = $lastParameter->getType();
    2086|                               }
    2087|

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined offset: 0", "/Users/wi1dcard/GitHub/larastan-variadic-model-scope/vendor/phpstan/phpstan/src/Analyser/NodeScopeResolver.php")
      /Users/wi1dcard/GitHub/larastan-variadic-model-scope/vendor/phpstan/phpstan/src/Analyser/NodeScopeResolver.php:2083

  2   PHPStan\Analyser\NodeScopeResolver::processArgs(Object(Mockery_1_PHPStan_Reflection_FunctionVariantWithPhpDocs_PHPStan_Reflection_FunctionVariantWithPhpDocs), Object(NunoMaduro\Larastan\Analyser\Scope), Object(Closure), Object(PHPStan\Analyser\ExpressionContext))
      /Users/wi1dcard/GitHub/larastan-variadic-model-scope/vendor/phpstan/phpstan/src/Analyser/NodeScopeResolver.php:1470

  Please use the argument -v to see more details.
```

**Comment by ondrejmirtes** [comment]
It's still the same result. Could you run it while commenting out these two lines in bootstrap.php? https://github.com/nunomaduro/larastan/blob/master/bootstrap.php#L26-L30

Or, ideally, click through them and comment out setting a custom error handler in Laravel.

**Comment by wi1dcard** [comment]
Finally get the details:

```
   ErrorException  : Undefined offset: 0

  at /larastan-variadic-model-scope/vendor/phpstan/phpstan/src/Analyser/NodeScopeResolver.php:2083
    2079| 				if (isset($parameters[$i])) {
    2080| 					$assignByReference = $parameters[$i]->passedByReference()->createsNewVariable();
    2081| 					$parameterType = $parameters[$i]->getType();
    2082| 				} elseif (count($parameters) > 0 && $parametersAcceptor->isVariadic()) {
  > 2083| 					$lastParameter = $parameters[count($parameters) - 1];
    2084| 					$assignByReference = $lastParameter->passedByReference()->createsNewVariable();
    2085| 					$parameterType = $lastParameter->getType();
    2086| 				}
    2087|

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined offset: 0", "/larastan-variadic-model-scope/vendor/phpstan/phpstan/src/Analyser/NodeScopeResolver.php")
      /larastan-variadic-model-scope/vendor/phpstan/phpstan/src/Analyser/NodeScopeResolver.php:2083

  2   PHPStan\Analyser\NodeScopeResolver::processArgs(Object(Mockery_1_PHPStan_Reflection_FunctionVariantWithPhpDocs_PHPStan_Reflection_FunctionVariantWithPhpDocs), Object(NunoMaduro\Larastan\Analyser\Scope), Object(Closure), Object(PHPStan\Analyser\ExpressionContext))
      /larastan-variadic-model-scope/vendor/phpstan/phpstan/src/Analyser/NodeScopeResolver.php:1470

  3   PHPStan\Analyser\NodeScopeResolver::processExprNode(Object(PhpParser\Node\Expr\MethodCall), Object(NunoMaduro\Larastan\Analyser\Scope), Object(Closure), Object(PHPStan\Analyser\ExpressionContext))
      /larastan-variadic-model-scope/vendor/phpstan/phpstan/src/Analyser/NodeScopeResolver.php:452

  4   PHPStan\Analyser\NodeScopeResolver::processStmtNode(Object(PhpParser\Node\Stmt\Expression), Object(NunoMaduro\Larastan\Analyser\Scope), Object(Closure))
      /larastan-variadic-model-scope/vendor/phpstan/phpstan/src/Analyser/NodeScopeResolver.php:237

  5   PHPStan\Analyser\NodeScopeResolver::processStmtNodes(Object(PhpParser\Node\Stmt\ClassMethod), Object(NunoMaduro\Larastan\Analyser\Scope), Object(Closure))
      /larastan-variadic-model-scope/vendor/phpstan/phpstan/src/Analyser/NodeScopeResolver.php:407

  6   PHPStan\Analyser\NodeScopeResolver::processStmtNode(Object(PhpParser\Node\Stmt\ClassMethod), Object(NunoMaduro\Larastan\Analyser\Scope), Object(Closure))
      /larastan-variadic-model-scope/vendor/phpstan/phpstan/src/Analyser/NodeScopeResolver.php:237

  7   PHPStan\Analyser\NodeScopeResolver::processStmtNodes(Object(PhpParser\Node\Stmt\Class_), Object(NunoMaduro\Larastan\Analyser\Scope), Object(Closure))
      /larastan-variadic-model-scope/vendor/phpstan/phpstan/src/Analyser/NodeScopeResolver.php:487

  8   PHPStan\Analyser\NodeScopeResolver::processStmtNode(Object(PhpParser\Node\Stmt\Class_), Object(NunoMaduro\Larastan\Analyser\Scope), Object(Closure))
      /larastan-variadic-model-scope/vendor/phpstan/phpstan/src/Analyser/NodeScopeResolver.php:237

  9   PHPStan\Analyser\NodeScopeResolver::processStmtNodes(Object(PhpParser\Node\Stmt\Namespace_), Object(NunoMaduro\Larastan\Analyser\Scope), Object(Closure))
      /larastan-variadic-model-scope/vendor/phpstan/phpstan/src/Analyser/NodeScopeResolver.php:470

  10  PHPStan\Analyser\NodeScopeResolver::processStmtNode(Object(PhpParser\Node\Stmt\Namespace_), Object(NunoMaduro\Larastan\Analyser\Scope), Object(Closure))
      /larastan-variadic-model-scope/vendor/phpstan/phpstan/src/Analyser/NodeScopeResolver.php:191

  11  PHPStan\Analyser\NodeScopeResolver::processNodes(Object(NunoMaduro\Larastan\Analyser\Scope), Object(Closure))
      /larastan-variadic-model-scope/vendor/phpstan/phpstan/src/Analyser/Analyser.php:198

  12  PHPStan\Analyser\Analyser::analyse(Object(Closure), Object(Closure))
      /larastan-variadic-model-scope/vendor/phpstan/phpstan/src/Command/AnalyseApplication.php:124

  13  PHPStan\Command\AnalyseApplication::analyse(Object(PHPStan\Command\ErrorsConsoleStyle), Object(PHPStan\Command\ErrorFormatter\TableErrorFormatter), "/larastan-variadic-model-scope/phpstan.neon")
      /larastan-variadic-model-scope/vendor/phpstan/phpstan/src/Command/AnalyseCommand.php:127

  14  PHPStan\Command\AnalyseCommand::execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /larastan-variadic-model-scope/vendor/symfony/console/Command/Command.php:255

  15  Symfony\Component\Console\Command\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /larastan-variadic-model-scope/vendor/symfony/console/Application.php:921

  16  Symfony\Component\Console\Application::doRunCommand(Object(PHPStan\Command\AnalyseCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /larastan-variadic-model-scope/vendor/symfony/console/Application.php:273

  17  Symfony\Component\Console\Application::doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /larastan-variadic-model-scope/vendor/symfony/console/Application.php:149

  18  Symfony\Component\Console\Application::run()
      /larastan-variadic-model-scope/vendor/phpstan/phpstan/bin/phpstan:62
```

**Comment by ondrejmirtes** [comment]
Since I fixed similar issue in macros in #298, I also attached the fix for this there.

**Comment by szepeviktor** [comment]
@wi1dcard Could you try the master branch?

**Comment by nunomaduro** [comment]
It's tagged, you can pull the latest version.

**Comment by wi1dcard** [comment]
Thank you guys, it's fixed!
