### ISSUE TITLE
PHPStan: Undefined variable: $this in Pest test clousure

### ISSUE THREAD

**Issue by fabioi** [nunomaduro/larastan#706]
- Larastan Version: 0.6.0

### Description

PHPStan complains $this variable is undefined in a Pest test. 

### Laravel code where the issue was found

```php
it('it gets the users index page', function () {
    $user = User::factory()->getStaffUser();

    $this->actingAs($user)->get(route('backend.users.index'))
        ->assertStatus(200);
});

```
Not sure if it's related to #42, wanted to ask if there is a way to fix this in PHPStan, thank you

**Comment by szepeviktor** [comment]
Yes, Larastan is not *yet*  able to `$this` in closures.

Please add `/** @var \Fully\Qualified\Class\Name $this */` and an empty line in top of the closure.

**Comment by nunomaduro** [comment]
@fabioi You can always use the Laravel plugin.

**Comment by fabioi** [comment]
Thanks a lot for the feedback / information

**Comment by trip-somers** [comment]
> @fabioi You can always use [the Laravel plugin](https://github.com/pestphp/pest-plugin-laravel).

I am using the plugin, and I still see this error for all of my Pest test closures. Am I missing something else?

**Comment by hansnn** [comment]
> Yes, Larastan is not _yet_ able to resolve `$this` in closures.

Any news regarding when/if Larastan will be able to resolve `$this` in closures (or at least in Pest tests) @szepeviktor?

**Comment by szepeviktor** [comment]
@hansnn I think this should be implemented on a per case basis.
Larastan has to know the class.

**Comment by leecolarelli-tgb** [comment]
Hi all. I am still unsure how to handle this. On latest versions of pest, laravel, larastan.

I am wanting to add a variable for the current file using `beforeEach()`. 

```php
/**
 * @var TestCase $this
 */
beforeEach(function (): void {
    $this->variableName = new ExampleClassname();
});
```

However, if I define $this as the Testcase class in a docblock, i.e. `/** @var TestCase $this */` then Larastan will obviously now give a `Access to an undefined property Tests\TestCase::$variableName` error.

If I have to define a class to append the property, then `beforeEach()` becomes a bit more cumbersome to use.

**Comment by szepeviktor** [comment]
Try `@var` inside the function.

**Comment by leecolarelli-tgb** [comment]
> Try `@var` inside the function.

I'm sorry, could you please give an example?

If you mean like this...

```
beforeEach(function (): void {
    /** @var TestCase $this */
    $this->variableName = new ExampleClassname();
});
```

then it results in two errors - `phpstan: Undefined variable: $this. phpstan: Variable $this in PHPDoc tag @var does not exist.`

**Comment by szepeviktor** [comment]
PHPStan lives in OOP world, binding closures is not fully supported.

**Comment by szepeviktor** [comment]
What is the result of adding a blank line after `@var`?

**Comment by leecolarelli-tgb** [comment]
> What is the result of adding a blank line after `@var`?

It results in the same errors. Also, I use Laravel Pint which will remove the blank line :D

**Comment by domioanna** [comment]
Any movement on this? I'm experiencing the same issue and would love to solve it.

**Comment by BertvanHoekelen** [comment]
@domioanna I think it was resolved with this https://github.com/pestphp/pest/commit/c65755725d777cf15c9a0a6fd66dc3a166ccafb3

**Comment by rburgst** [comment]
still getting this problem

**Comment by calebdw** [comment]
@rburgst, I tend to use `test()->` over `$this->` in tests for this reason. I've also stopped analyzing my tests with PHPStan / Larastan---there's often no benefit to doing so as they are going to be tested anyway (why test your tests 🙃 ?)

**Comment by rburgstaller** [comment]
Managed to fix it by using https://github.com/pestphp/pest-plugin-laravel. It makes the tests also read a lot nicer.

**Comment by ItsReddi** [comment]
Also still getting the error:
```neon 
includes:
    - vendor/larastan/larastan/extension.neon
    - vendor/nesbot/carbon/extension.neon
    - vendor/pestphp/pest/extension.neon

parameters:

    paths:
        - app/
        - modules/
        - tests/

    level: 8
```

- Empty laravel application / no skeleton / with pest
- Installed latest versions.

```php
<?php

test('returns a successful response', function () {
    $response = $this->get('/');
    $response->assertStatus(200);
});
```

```bash
 ------ ---------------------------------------------------------------- 
  Line   tests/Feature/ExampleTest.php                                   
 ------ ---------------------------------------------------------------- 
  :4     Call to an undefined method PHPUnit\Framework\TestCase::get().  
         🪪  method.notFound                                             
 ------ ---------------------------------------------------------------- 
```

**Comment by rburgstaller** [comment]
@ItsReddi see my previous post

**Comment by rooselle** [comment]
I have pest plugin laravel installed and I also have the error @leecolarelli-tgb mentions in this comment: https://github.com/larastan/larastan/issues/706#issuecomment-1833499140

**Comment by calebdw** [comment]
Instead of `$this`, I always use `test()` inside the closure

**Comment by rooselle** [comment]
I tried this too but then I get `Access to an undefined property Pest\PendingCalls\TestCall|Pest\Support\HigherOrderTapProxy::$myVariable`

**Comment by calebdw** [comment]
I also don't analyze my tests with phpstan--- there's really no reason to given that they're tested anyway in the pipeline

**Comment by a-coding-a** [comment]
I have the same problem with Laravel 12, default PEST setup. This includes the Pest Laravel plugin preinstalled. Replacing `$this` with `test()` gives a different error, `HigherOrderTapProxy`. 

Catching test errors in the pipeline is much slower than using static analysis to fix it beforehand. Just had to remove the tests from being analysed

**Comment by uh-zuh** [comment]
I've found a workaround for helper functions.

Add following function into `tests/Pest.php` and use `getTestCase()` instead of `test()`:
```php
function getTestCase(): TestCase
{
    // @phpstan-ignore staticMethod.internalClass, property.internalClass
    $test_case = \Pest\TestSuite::getInstance()->test;
    assert($test_case instanceof TestCase);
    return $test_case;
}
```

**Comment by uh-zuh** [comment]
And another workaround for test functions - add one `assert()` in the first line of every test:
```php
test('some test', function () {
    assert($this instanceof TestCase);

    $response = $this->get('/api/v1/...');
});
```

**Comment by calebdw** [comment]
I just use the `get()` pest function

**Comment by doraemonxxx** [comment]
```.php
use PHPUnit\Framework\TestCase;
expect()->extend('toBeOne', function (): mixed {
    /** @var TestCase $this */
    return $this->toBe(1);
});
```

What’s the solution? It seems the issue still isn’t resolved on my end.

pestphp/pest 1.23.1
pestphp/pest-plugin-laravel 1.4.0
phpstan/phpstan 1.8.11
phpunit/phpunit 9.5.10

**Comment by canvural** [comment]
> ```.php
> use PHPUnit\Framework\TestCase;
> expect()->extend('toBeOne', function (): mixed {
>     /** @var TestCase $this */
>     return $this->toBe(1);
> });
> ```
> 
> What’s the solution? It seems the issue still isn’t resolved on my end.
> 
> pestphp/pest 1.23.1
> pestphp/pest-plugin-laravel 1.4.0
> phpstan/phpstan 1.8.11
> phpunit/phpunit 9.5.10
> 

We do not support Pest. You can try asking in their repo maybe.

**Comment by doraemonxxx** [comment]
> > [@fabioi](https://github.com/fabioi) You can always use [the Laravel plugin](https://github.com/pestphp/pest-plugin-laravel).
> 
> I am using the plugin, and I still see this error for all of my Pest test closures. Am I missing something else?
> 
> NOTE: I am using the 1.x branch because the codebase is using Laravel 8.x.

Same here. I don’t want to upgrade Laravel or other packages since the project is locked to these versions:
Laravel 8.75 and PHP 8.2.25.


_Edit_
Lol never mind! But thanks in advance to whoever ends up helping 😊
